### ISSUE TITLE
Player editing not working properly

### ISSUE THREAD

**Issue by ManuelKetisch** [xAranaktu/FIFA-22-Live-Editor#10]
The Editor does not seem to apply editied values.
In the editor the modified values show. 
In game they do show for a single game and then return back to unmodified values.

**Comment by xAranaktu** [comment]
Player career mode? [Not a bug](https://github.com/xAranaktu/FIFA-22-Live-Editor/wiki/Editing-Player#player-career-mode)
The only way to increase attributes there is to use the Cheat Table and [999 Skill Points Cheat](https://github.com/xAranaktu/FIFA-22-CM-Cheat-Table/wiki/999-Skill-Points)
