### ISSUE TITLE
Game crashes on startup after update.

### ISSUE THREAD

**Issue by Niicoo001** [xAranaktu/FIFA-22-Live-Editor#11]
After an update that was released today, my game always crashes on startup if I had previously launched the Live Editor. 
When I start the game without Live Editor, it starts normally.

**Comment by xAranaktu** [comment]
Works fine for me.
The screen with patch notes may cause the crash. You need to go through it before you run the live editor.

**Comment by Niicoo001** [comment]
When I start the game without the editor, it starts normally and I don't get any patch notes. 
When I start the game with the editor, the game launcher opens and when I press Start Game, a black game screen appears and the game closes without any message.

**Comment by Niicoo001** [comment]
The following error is in the logs:
[ERROR] [HookMgr::AddHook] PLH failed fnCFStryFindFile

**Comment by xAranaktu** [comment]
Run the live editor after you enter main menu. Otherwise idk. maybe delete the live editor and LiveEditorMods folder (that you should have in your game installation dir) and download live editor again.

**Comment by Niicoo001** [comment]
I started the Live Editor when I was in the main menu. This worked and the editor started.
After that I tried to start the editor before starting the game and it worked again then.
Thanks for the help!

**Comment by Niicoo001** [comment]
I started the Live Editor when I was in the main menu. This worked and the editor started.
After that I tried to start the editor before starting the game and it worked again then.
Thanks for the help!
