### ISSUE TITLE
Squad max size

### ISSUE THREAD

**Issue by AngelFireLA** [xAranaktu/FIFA-22-Live-Editor#12]
How to make minimum and maximum squad size, bigger or smaller ?
I know you could a few years ago with cheat engine, but idk how to do it (if it's possible) now

**Comment by xAranaktu** [comment]
There wasn't ever feature like that in my cheat tables.
The only option that can change that I know of is "MAX_SQUAD_SIZE" in cmsettings.ini.
But making it above 52 will surely break your career save.

**Comment by AngelFireLA** [comment]
It was in fifa 19 cheat table, but yeah, I think it's what you said, one of the ini files, thank you
