### ISSUE TITLE
Unable to edit a players injury via Live Editor

### ISSUE THREAD

**Issue by Pyrolax** [xAranaktu/FIFA-22-Live-Editor#2]
When my player got injured in CM, I opened the live editor to remove the injury (it was like 8 months)
On other players it allows me to use a dropdown box to change if they are injured or not, and when I open my teams player there is no dropdown to change this.
![image](https://user-images.githubusercontent.com/38303306/147412640-50aa9baa-bd51-4c57-a438-f01c2c77b39f.png)

**Comment by xAranaktu** [comment]
I need your CM save to be able to check this.

**Comment by Pyrolax** [comment]
I'll send it over now, one second

**Comment by Pyrolax** [comment]
https://mega.nz/file/pdEiDRIZ#6w9v6gjyD5FG1OZBz8V3Maiwed286sFMihkqgWfhc6k

GitHub wouldn't let me upload directly

**Comment by xAranaktu** [comment]
Should be fixed in v22.1.1.1
Closing for now.
