### ISSUE TITLE
FIFA 22 crashes when I try to edit a player.

### ISSUE THREAD

**Issue by LouieJ93** [xAranaktu/FIFA-22-Live-Editor#3]
Hi Aranaktu,

Thank you for making this live editor, I forward to using it! Unforunately I don't use discord so I can't post the issue there but when I try to edit a player in my manager career mode, the game crashes when I select a player.

I go into my save, go into my team sheet and open the player editor. As soon as I select any player from the list, no information loads and my FIFA 22 game just closes.

Am I doing something wrong?

Thank you and any help is appreciated.

- LouieJ93

**Comment by xAranaktu** [comment]
First of all, make sure you are using latest version of the tool (v22.1.1.1)
Then read [Troubleshooting](https://github.com/xAranaktu/FIFA-22-Live-Editor/wiki/Troubleshooting)
If the game still will crash send the log file.

**Comment by LouieJ93** [comment]
Thank you so much, I followed the troubleshooting directions and it works perfectly! Once again, thank you for creating this and making my career mode experience much more exciting! I look forward to your future work!
