### ISSUE TITLE
Keeps "Waiting for FIFA22.exe process"

### ISSUE THREAD

**Issue by Sthyrk** [xAranaktu/FIFA-22-Live-Editor#4]
I open the game, run the program and it keeps "Waiting for FIFA22.exe process". I can't open settings either, there's a screen with nothing.

**Comment by xAranaktu** [comment]
I guess you are using trial game version, so you need to change `PROC_NAME` in `launcher_config.ini`
Open `launcher_config.ini` with notepad and then change
```
PROC_NAME=FIFA22.exe
```
to
```
PROC_NAME=FIFA22_Trial.exe
```

If you have full version then I don't know. Make sure the process name is `FIFA22.exe` and your antivirus doesn't block anything, or just use [Other DLL Injector](https://github.com/xAranaktu/FIFA-22-Live-Editor/wiki/Using-other-DLL-Injectors)

**Comment by Sthyrk** [comment]
It worked now, I bought the game but I had 10 hours to use, I think I was using them before, now it's working correctly. Thank you, nice work even, it helps a lot!
