### ISSUE TITLE
Fifa live editor not detecting fifa22.exe

### ISSUE THREAD

**Issue by santmalvin23** [xAranaktu/FIFA-22-Live-Editor#5]
hi, I got a new problem today my fifa live editor didn't detect my fifa22.exe . Already tried to restart a few times but still have the same result. 
![error fifa](https://user-images.githubusercontent.com/92980097/149130845-b44a052b-8243-4ad0-856d-9c33f5135d15.png)

**Comment by xAranaktu** [comment]
#4
